# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gan_testbed.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 682)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_genImage = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_genImage.setGeometry(QtCore.QRect(20, 10, 301, 301))
        self.groupBox_genImage.setObjectName("groupBox_genImage")
        self.label_genImage = QtWidgets.QLabel(self.groupBox_genImage)
        self.label_genImage.setGeometry(QtCore.QRect(10, 30, 281, 261))
        self.label_genImage.setAlignment(QtCore.Qt.AlignCenter)
        self.label_genImage.setObjectName("label_genImage")
        self.groupBox_modelBuilder = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_modelBuilder.setGeometry(QtCore.QRect(330, 10, 771, 441))
        self.groupBox_modelBuilder.setObjectName("groupBox_modelBuilder")
        self.groupBox_library = QtWidgets.QGroupBox(self.groupBox_modelBuilder)
        self.groupBox_library.setGeometry(QtCore.QRect(10, 20, 181, 101))
        self.groupBox_library.setObjectName("groupBox_library")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_library)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 169, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_tensorflow = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_tensorflow.setChecked(True)
        self.radioButton_tensorflow.setObjectName("radioButton_tensorflow")
        self.gridLayout.addWidget(self.radioButton_tensorflow, 0, 0, 1, 1)
        self.radioButton_pytorch = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_pytorch.setChecked(False)
        self.radioButton_pytorch.setObjectName("radioButton_pytorch")
        self.gridLayout.addWidget(self.radioButton_pytorch, 1, 0, 1, 1)
        self.checkBox_gpuMode = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_gpuMode.setObjectName("checkBox_gpuMode")
        self.gridLayout.addWidget(self.checkBox_gpuMode, 1, 1, 1, 1)
        self.groupBox_input = QtWidgets.QGroupBox(self.groupBox_modelBuilder)
        self.groupBox_input.setGeometry(QtCore.QRect(200, 20, 201, 121))
        self.groupBox_input.setObjectName("groupBox_input")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_input)
        self.layoutWidget1.setGeometry(QtCore.QRect(12, 30, 181, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_input = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_input.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_input.setObjectName("gridLayout_input")
        self.comboBox_dataset = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_dataset.setObjectName("comboBox_dataset")
        self.gridLayout_input.addWidget(self.comboBox_dataset, 1, 1, 1, 1)
        self.label_dataset = QtWidgets.QLabel(self.layoutWidget1)
        self.label_dataset.setObjectName("label_dataset")
        self.gridLayout_input.addWidget(self.label_dataset, 1, 0, 1, 1)
        self.label_modelName = QtWidgets.QLabel(self.layoutWidget1)
        self.label_modelName.setObjectName("label_modelName")
        self.gridLayout_input.addWidget(self.label_modelName, 0, 0, 1, 1)
        self.comboBox_model = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_model.setObjectName("comboBox_model")
        self.gridLayout_input.addWidget(self.comboBox_model, 0, 1, 1, 1)
        self.label_batchSize = QtWidgets.QLabel(self.layoutWidget1)
        self.label_batchSize.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_batchSize.setObjectName("label_batchSize")
        self.gridLayout_input.addWidget(self.label_batchSize, 2, 0, 1, 1)
        self.spinBox_batchSize = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_batchSize.setMaximum(10000)
        self.spinBox_batchSize.setSingleStep(1)
        self.spinBox_batchSize.setProperty("value", 100)
        self.spinBox_batchSize.setObjectName("spinBox_batchSize")
        self.gridLayout_input.addWidget(self.spinBox_batchSize, 2, 1, 1, 1)
        self.groupBox_hyperParam = QtWidgets.QGroupBox(self.groupBox_modelBuilder)
        self.groupBox_hyperParam.setGeometry(QtCore.QRect(10, 160, 391, 241))
        self.groupBox_hyperParam.setObjectName("groupBox_hyperParam")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_hyperParam)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 31, 371, 201))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_actFnDisc = QtWidgets.QHBoxLayout()
        self.horizontalLayout_actFnDisc.setObjectName("horizontalLayout_actFnDisc")
        self.checkBox_actFnDisc = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_actFnDisc.setChecked(True)
        self.checkBox_actFnDisc.setObjectName("checkBox_actFnDisc")
        self.horizontalLayout_actFnDisc.addWidget(self.checkBox_actFnDisc)
        self.comboBox_actFnDisc = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_actFnDisc.setObjectName("comboBox_actFnDisc")
        self.horizontalLayout_actFnDisc.addWidget(self.comboBox_actFnDisc)
        self.verticalLayout.addLayout(self.horizontalLayout_actFnDisc)
        self.horizontalLayout_actFnGen = QtWidgets.QHBoxLayout()
        self.horizontalLayout_actFnGen.setObjectName("horizontalLayout_actFnGen")
        self.checkBox_actFnGen = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_actFnGen.setChecked(True)
        self.checkBox_actFnGen.setObjectName("checkBox_actFnGen")
        self.horizontalLayout_actFnGen.addWidget(self.checkBox_actFnGen)
        self.comboBox_actFnGen = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_actFnGen.setObjectName("comboBox_actFnGen")
        self.horizontalLayout_actFnGen.addWidget(self.comboBox_actFnGen)
        self.verticalLayout.addLayout(self.horizontalLayout_actFnGen)
        self.horizontalLayout_initFn = QtWidgets.QHBoxLayout()
        self.horizontalLayout_initFn.setObjectName("horizontalLayout_initFn")
        self.checkBox_initFn = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_initFn.setChecked(True)
        self.checkBox_initFn.setObjectName("checkBox_initFn")
        self.horizontalLayout_initFn.addWidget(self.checkBox_initFn)
        self.comboBox_initFn = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_initFn.setObjectName("comboBox_initFn")
        self.horizontalLayout_initFn.addWidget(self.comboBox_initFn)
        self.verticalLayout.addLayout(self.horizontalLayout_initFn)
        self.horizontalLayout_hyperParam = QtWidgets.QHBoxLayout()
        self.horizontalLayout_hyperParam.setObjectName("horizontalLayout_hyperParam")
        self.label_hyperParam1 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_hyperParam1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hyperParam1.setObjectName("label_hyperParam1")
        self.horizontalLayout_hyperParam.addWidget(self.label_hyperParam1)
        self.doubleSpinBox_hyperParam1 = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_hyperParam1.setDecimals(1)
        self.doubleSpinBox_hyperParam1.setMaximum(1.0)
        self.doubleSpinBox_hyperParam1.setSingleStep(0.1)
        self.doubleSpinBox_hyperParam1.setProperty("value", 0.7)
        self.doubleSpinBox_hyperParam1.setObjectName("doubleSpinBox_hyperParam1")
        self.horizontalLayout_hyperParam.addWidget(self.doubleSpinBox_hyperParam1)
        self.label_hyperParam2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_hyperParam2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hyperParam2.setObjectName("label_hyperParam2")
        self.horizontalLayout_hyperParam.addWidget(self.label_hyperParam2)
        self.doubleSpinBox_hyperParam2 = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_hyperParam2.setDecimals(1)
        self.doubleSpinBox_hyperParam2.setMaximum(1.0)
        self.doubleSpinBox_hyperParam2.setSingleStep(0.1)
        self.doubleSpinBox_hyperParam2.setProperty("value", 0.7)
        self.doubleSpinBox_hyperParam2.setObjectName("doubleSpinBox_hyperParam2")
        self.horizontalLayout_hyperParam.addWidget(self.doubleSpinBox_hyperParam2)
        self.verticalLayout.addLayout(self.horizontalLayout_hyperParam)
        self.horizontalLayout_batchNorm = QtWidgets.QHBoxLayout()
        self.horizontalLayout_batchNorm.setObjectName("horizontalLayout_batchNorm")
        self.checkBox_bathNorm = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_bathNorm.setObjectName("checkBox_bathNorm")
        self.horizontalLayout_batchNorm.addWidget(self.checkBox_bathNorm)
        self.verticalLayout.addLayout(self.horizontalLayout_batchNorm)
        self.pushButton_buildModel = QtWidgets.QPushButton(self.groupBox_modelBuilder)
        self.pushButton_buildModel.setGeometry(QtCore.QRect(550, 400, 101, 31))
        self.pushButton_buildModel.setObjectName("pushButton_buildModel")
        self.pushButton_clearModel = QtWidgets.QPushButton(self.groupBox_modelBuilder)
        self.pushButton_clearModel.setGeometry(QtCore.QRect(660, 400, 101, 31))
        self.pushButton_clearModel.setObjectName("pushButton_clearModel")
        self.scrollArea_modelViewer = QtWidgets.QScrollArea(self.groupBox_modelBuilder)
        self.scrollArea_modelViewer.setGeometry(QtCore.QRect(420, 30, 331, 361))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_modelViewer.sizePolicy().hasHeightForWidth())
        self.scrollArea_modelViewer.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 157, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 157, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 157, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 157, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 157, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 157, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.scrollArea_modelViewer.setPalette(palette)
        self.scrollArea_modelViewer.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_modelViewer.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_modelViewer.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_modelViewer.setWidgetResizable(False)
        self.scrollArea_modelViewer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea_modelViewer.setObjectName("scrollArea_modelViewer")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 217, 407))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_modelViewer.setWidget(self.scrollAreaWidgetContents)
        self.groupBox_training = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_training.setGeometry(QtCore.QRect(720, 460, 381, 191))
        self.groupBox_training.setObjectName("groupBox_training")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_training)
        self.layoutWidget3.setGeometry(QtCore.QRect(16, 30, 241, 151))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_training = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_training.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_training.setObjectName("gridLayout_training")
        self.label_optimizer = QtWidgets.QLabel(self.layoutWidget3)
        self.label_optimizer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_optimizer.setObjectName("label_optimizer")
        self.gridLayout_training.addWidget(self.label_optimizer, 0, 0, 1, 1)
        self.comboBox_optimizer = QtWidgets.QComboBox(self.layoutWidget3)
        self.comboBox_optimizer.setObjectName("comboBox_optimizer")
        self.gridLayout_training.addWidget(self.comboBox_optimizer, 0, 1, 1, 1)
        self.label_numEpochs = QtWidgets.QLabel(self.layoutWidget3)
        self.label_numEpochs.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_numEpochs.setObjectName("label_numEpochs")
        self.gridLayout_training.addWidget(self.label_numEpochs, 1, 0, 1, 1)
        self.spinBox_numEpochs = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_numEpochs.setMaximum(100000)
        self.spinBox_numEpochs.setProperty("value", 20)
        self.spinBox_numEpochs.setObjectName("spinBox_numEpochs")
        self.gridLayout_training.addWidget(self.spinBox_numEpochs, 1, 1, 1, 1)
        self.label_learningRateD = QtWidgets.QLabel(self.layoutWidget3)
        self.label_learningRateD.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_learningRateD.setObjectName("label_learningRateD")
        self.gridLayout_training.addWidget(self.label_learningRateD, 2, 0, 1, 1)
        self.lineEdit_learningRateG = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_learningRateG.setReadOnly(False)
        self.lineEdit_learningRateG.setObjectName("lineEdit_learningRateG")
        self.gridLayout_training.addWidget(self.lineEdit_learningRateG, 2, 1, 1, 1)
        self.label_learningRateG = QtWidgets.QLabel(self.layoutWidget3)
        self.label_learningRateG.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_learningRateG.setObjectName("label_learningRateG")
        self.gridLayout_training.addWidget(self.label_learningRateG, 3, 0, 1, 1)
        self.lineEdit_learningRateD = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_learningRateD.setReadOnly(False)
        self.lineEdit_learningRateD.setObjectName("lineEdit_learningRateD")
        self.gridLayout_training.addWidget(self.lineEdit_learningRateD, 3, 1, 1, 1)
        self.pushButton_trainModel = QtWidgets.QPushButton(self.groupBox_training)
        self.pushButton_trainModel.setGeometry(QtCore.QRect(270, 30, 101, 31))
        self.pushButton_trainModel.setObjectName("pushButton_trainModel")
        self.pushButton_evaluation = QtWidgets.QPushButton(self.groupBox_training)
        self.pushButton_evaluation.setGeometry(QtCore.QRect(270, 70, 101, 31))
        self.pushButton_evaluation.setObjectName("pushButton_evaluation")
        self.pushButton_tensorBoard = QtWidgets.QPushButton(self.groupBox_training)
        self.pushButton_tensorBoard.setGeometry(QtCore.QRect(270, 110, 101, 31))
        self.pushButton_tensorBoard.setObjectName("pushButton_tensorBoard")
        self.pushButton_Exit = QtWidgets.QPushButton(self.groupBox_training)
        self.pushButton_Exit.setGeometry(QtCore.QRect(270, 150, 101, 31))
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.groupBox_plotPrediction = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_plotPrediction.setGeometry(QtCore.QRect(20, 330, 301, 221))
        self.groupBox_plotPrediction.setObjectName("groupBox_plotPrediction")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_plotPrediction)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 29, 281, 181))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_plotPrediction = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_plotPrediction.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_plotPrediction.setObjectName("horizontalLayout_plotPrediction")
        self.scrollArea_log = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_log.setGeometry(QtCore.QRect(330, 470, 341, 181))
        self.scrollArea_log.setWidgetResizable(True)
        self.scrollArea_log.setObjectName("scrollArea_log")
        self.scrollAreaWidgetContents_log = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_log.setGeometry(QtCore.QRect(0, 0, 339, 179))
        self.scrollAreaWidgetContents_log.setObjectName("scrollAreaWidgetContents_log")
        self.textEdit_log = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_log)
        self.textEdit_log.setGeometry(QtCore.QRect(0, 0, 341, 181))
        self.textEdit_log.setObjectName("textEdit_log")
        self.scrollArea_log.setWidget(self.scrollAreaWidgetContents_log)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MNIST Testbed"))
        self.groupBox_genImage.setTitle(_translate("MainWindow", "Generated image"))
        self.label_genImage.setText(_translate("MainWindow", "Result image"))
        self.groupBox_modelBuilder.setTitle(_translate("MainWindow", "Model Builder"))
        self.groupBox_library.setTitle(_translate("MainWindow", "Library"))
        self.radioButton_tensorflow.setText(_translate("MainWindow", "TensorFlow"))
        self.radioButton_pytorch.setText(_translate("MainWindow", "PyTorch"))
        self.checkBox_gpuMode.setText(_translate("MainWindow", "use GPU"))
        self.groupBox_input.setTitle(_translate("MainWindow", "Input / Output"))
        self.label_dataset.setText(_translate("MainWindow", "Dataset"))
        self.label_modelName.setText(_translate("MainWindow", "Model name"))
        self.label_batchSize.setText(_translate("MainWindow", "Batch size"))
        self.groupBox_hyperParam.setTitle(_translate("MainWindow", "Hyper Parameters"))
        self.checkBox_actFnDisc.setText(_translate("MainWindow", "Activation for discriminator"))
        self.checkBox_actFnGen.setText(_translate("MainWindow", "Activation for generator"))
        self.checkBox_initFn.setText(_translate("MainWindow", "Weight initializer"))
        self.label_hyperParam1.setText(_translate("MainWindow", "Hyper parameter 1"))
        self.label_hyperParam2.setText(_translate("MainWindow", "Hyper parameter 2"))
        self.checkBox_bathNorm.setText(_translate("MainWindow", "Batch normalization"))
        self.pushButton_buildModel.setText(_translate("MainWindow", "Build model"))
        self.pushButton_clearModel.setText(_translate("MainWindow", "Clear model"))
        self.groupBox_training.setTitle(_translate("MainWindow", "Training"))
        self.label_optimizer.setText(_translate("MainWindow", "Optimizer"))
        self.label_numEpochs.setText(_translate("MainWindow", "# of Epochs"))
        self.label_learningRateD.setText(_translate("MainWindow", "Learning rate for G"))
        self.lineEdit_learningRateG.setText(_translate("MainWindow", "0.0002"))
        self.label_learningRateG.setText(_translate("MainWindow", "Learning rate for D"))
        self.lineEdit_learningRateD.setText(_translate("MainWindow", "0.0002"))
        self.pushButton_trainModel.setText(_translate("MainWindow", "Train model"))
        self.pushButton_evaluation.setText(_translate("MainWindow", "Evaluation"))
        self.pushButton_tensorBoard.setText(_translate("MainWindow", "TensorBoard"))
        self.pushButton_Exit.setText(_translate("MainWindow", "Exit"))
        self.groupBox_plotPrediction.setTitle(_translate("MainWindow", "GAN losses"))

